apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktetoing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktetoing
  template:
    metadata:
      labels:
        app: oktetoing
    spec:
      containers:
      - image: okteto.dev/oktetoing:latest
        name: oktetoing
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "446d7473-3ac8-42a1-9ca1-9ba4c60ffb47"
        - name: Vless_Path
          value: "/vl51515"
        - name: Vmess_UUID
          value: "446d7473-3ac8-42a1-9ca1-9ba4c60ffb47"
        - name: Vmess_Path
          value: "/vm161616"
        - name: Share_Path
          value: "/v2link"
